#!/usr/bin/env bash

# Accepted values : True/TRUE or False/FALSE
export PYPP11_PYTEST_RUN_CPP_TESTS=TRUE

export BUILD_MEC_MODULE1_CPP=TRUE
export BUILD_MEC_MODULE1_PYTHON=TRUE

export BUILD_MEC_MODULE2_CPP=TRUE
export BUILD_MEC_MODULE2_PYTHON=TRUE

export BUILD_MEC_MODULE3_CPP=TRUE
export BUILD_MEC_MODULE3_PYTHON=TRUE
